---
- name: Deploy environment for regular user
  hosts: all
  roles:
    - common
    - alacritty
    - tmux

- name: Deploy environment for root user too
  hosts: all
  become: true
  roles:
    - alacritty
    - tmux
