---
- name: Install zsh # noqa: package-latest
  ansible.builtin.package:
    name:
      - zsh
      - util-linux-user
      - fzf
    state: latest
  become: true
  tags:
    - zsh

- name: Check presence oh-my-zsh
  ansible.builtin.stat:
    path: "~/.oh-my-zsh"
  register: oh_my_zsh_dir
  tags:
    - zsh

- name: Download and install oh-my-zsh if it were not installed before
  block:
    - name: Create temp dir for oh-my-zsh
      ansible.builtin.tempfile:
        state: directory
        suffix: zsh_temp
      register: zsh_temp
    - name: Download oh-my-zsh install file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "{{ zsh_temp.path }}/install.sh"
        mode: "0750"
      when: zsh_temp.path is defined
    - name: Start install oh-my-zsh
      ansible.builtin.command:
        cmd: "{{ zsh_temp.path }}/install.sh --unattended"
      changed_when: false
      when: zsh_temp.path is defined
    - name: Remove temp dir
      ansible.builtin.file:
        path: "{{ zsh_temp.path }}"
        state: absent
      when: zsh_temp.path is defined
  when: oh_my_zsh_dir.stat.isdir is not defined
  tags:
    - zsh

- name: Install/update zsh-autosuggestions plugin # noqa: latest[git]
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: true
    force: true
  tags:
    - zsh

- name: Install/update zsh-syntax-highlighting plugin # noqa: latest[git]
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: true
    force: true
  tags:
    - zsh

- name: Install/update zsh-completions plugin # noqa: latest[git]
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-completions.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    update: true
    force: true
  tags:
    - zsh

- name: Install/update fzf-tab plugin # noqa: latest[git]
  ansible.builtin.git:
    repo: "https://github.com/Aloxaf/fzf-tab.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/fzf-tab"
    update: true
    force: true
  tags:
    - zsh

- name: Copy zsh config
  ansible.builtin.template:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0750"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - zsh

- name: Change zsh to default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  tags:
    - zsh
