export ZSH="$HOME/.oh-my-zsh"
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
ZSH_THEME=""
plugins=(git tmux brew zsh-autosuggestions zsh-completions fzf zsh-syntax-highlighting)
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
source "$ZSH/oh-my-zsh.sh"
export GPG_TTY=$(tty)
export GNUPGHOME=$HOME/.gnupg
eval "$(starship init zsh)"
alias ll="ls -alh --color=always"
export PATH="$HOME/.local/bin:$PATH"
