---
- name: Deploy regular user
  hosts: all
  roles:
    - role: common
    - role: alacritty
    - role: starship
    - role: tmux
    - role: zsh
    - role: vim

- name: Deploy for root
  hosts: all
  become: true
  roles:
    - role: alacritty
    - role: starship
    - role: tmux
    - role: zsh
    - role: vim
