---
- name: Deploy regular user
  hosts: all
  roles:
    # - common
    - role: alacritty
    - role: starship
    - role: tmux
    - role: zsh

- name: Deploy for root
  hosts: all
  become: true
  roles:
    - role: alacritty
    - role: starship
    - role: tmux
    - role: zsh
