---
- name: Deploy regular user
  hosts: all
  roles:
    # - common
    - role: alacritty
    - role: starship
    # - tmux
    # - zsh

- name: Deploy for root
  hosts: all
  become: true
  roles:
    - role: alacritty
    - role: starship
    # - tmux
    # - zsh
