---
# Fonts: Fira Code and Fira Sans
- name: Install fonts # noqa: package-latest
  ansible.builtin.package:
    name:
      - fira-code-fonts
      - mozilla-fira-fonts-common
      - mozilla-fira-mono-fonts
      - mozilla-fira-sans-fonts
    state: latest
  become: true
  tags:
    - fonts

# Git ignore file
- name: Install git # noqa: package-latest
  ansible.builtin.package:
    name: git
    state: latest
  become: true
  tags:
    - git

- name: Copy git ignore file
  ansible.builtin.template:
    src: ".gitignore_global"
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - git

- name: Pass git config # noqa: command-instead-of-module
  ansible.builtin.shell: |
    git config --global {{ item }}
  changed_when: false
  loop:
    - "core.excludesfile {{ ansible_user_dir }}/.gitignore_global"
    - "user.name {{ git.name }}"
    - "user.email {{ git.email }}"
  tags:
    - git

# Tuned
- name: Tuned block
  block:
    - name: Install tuned # noqa: package-latest
      ansible.builtin.package:
        name: tuned
        state: latest
    - name: Config tuned
      ansible.builtin.shell: |
        tuned-adm profile balanced
      changed_when: false
    - name: Enable tuned
      ansible.builtin.service:
        name: tuned
        enabled: true
        state: started
  become: true
  tags:
    - tuned
#
## VS code
# - name: VScode block
#  block:
#    - name: add code repos
#      yum_repository:
#        name: "code"
#        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
#        description: "Visual Studio Code"
#        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
#        state: present
#        gpgcheck: true
#        enabled: true
#
#    - name: install code
#      dnf:
#        name:
#          - code
#        state: latest
#  become: true
#  tags:
#    - code
#
## Lynis
# - name: Lynis block
#  block:
#    - name: add lynis repos
#      yum_repository:
#        name: "lynis"
#        baseurl: "https://packages.cisofy.com/community/lynis/rpm/"
#        description: "CISOfy Software - Lynis package"
#        gpgkey: "https://packages.cisofy.com/keys/cisofy-software-rpms-public.key"
#        state: present
#        gpgcheck: true
#        enabled: true
#
#    - name: install lynis
#      dnf:
#        name:
#          - lynis
#        state: latest
#  become: true
#  tags:
#    - lynis
#
## Rkhunter
# - name: install rkhunter
#  dnf:
#    name:
#      - rkhunter
#    state: latest
#  become: true
#  tags:
#    - rkhunter

# Sysctl
- name: Copy sysctl.conf
  ansible.builtin.template:
    src: "10-custom-tune.conf"
    dest: "/etc/sysctl.d/10-custom-tune.conf"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
  tags:
    - sysctl
