---
- name: Install starship # noqa: package-latest
  ansible.builtin.package:
    name: starship
    state: latest
  become: true
  tags:
    - starship

- name: Copy configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/{{ item }}"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  loop:
    - starship.toml
  tags:
    - starship
