---
- name: Install starship # noqa: package-latest
  ansible.builtin.package:
    name: starship
    state: latest
  become: true
  tags:
    - starship

- name: Copy configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/{{ item }}"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  loop:
    - starship.toml
  tags:
    - starship

- name: Activate prompt zsh
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: 'eval "$(starship init zsh)"'
  when: ansible_user_shell == "/usr/bin/zsh"
  tags:
    - starship

- name: Activate prompt bash
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: 'eval "$(starship init bash)"'
  when: ansible_user_shell == "/usr/bin/bash"
  tags:
    - starship
