---
- name: Install vim # noqa: package-latest
  ansible.builtin.package:
    name: vim
    state: latest
  become: true
  tags:
    - vim

- name: Copy vim config
  ansible.builtin.template:
    src: ".vimrc"
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - vim
