---
- name: Install alacritty # noqa: package-latest
  ansible.builtin.package:
    name: alacritty
    state: latest
  become: true
  tags:
    - alacritty

- name: Create config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    mode: "0750"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - alacritty

- name: Copy configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/alacritty/{{ item }}"
    mode: "0640"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  loop:
    - alacritty.toml
    - material_theme_mod.toml
  tags:
    - alacritty
